command /퀘스트:
	trigger:
		set {_questGUI} to chest inventory with 3 rows named "퀘스트 목록"
		set slot 10 of {_questGUI} to map named "&a&l일일 퀘스트" with lore "&7클릭 하여 일일퀘스트 목록을 확인합니다."
		set slot 13 of {_questGUI} to writable book named "&e&l메인 퀘스트" with lore "&7클릭 하여 메인퀘스트 목록을 확인합니다."
		set slot 16 of {_questGUI} to spyglass named "&b&l기타 퀘스트" with lore "&7클릭 하여 기타퀘스트 목록을 확인합니다."
		open {_questGUI} to player