command /히든보스오픈:
	permission: op
	trigger:
		broadcast ""
		broadcast "&e&l[&e★&e&l] &a&l많은 낭만들의 응원&f으로 &d낭만 에너지&f가 모여 &c&l미지의 포탈&f이 생겼습니다."
		broadcast ""
		loop all players:
			play sound "block.end_portal.spawn" to loop-player


command /관리자명령어_도움말:
    permission: op
    trigger:
        send "/tr : 쓰레기통 (임시)" to player
        send "/관리자명령어_ : 까지 하면 자동완성으로 쫘라락~ " to player
        send "/테스트강화 , /강화성공확률지정 (값) , /횟수초기화: 강화 테스트용" to player
        send "/world spawn , /warp newbuild : 스폰 월드로 감" to player
        send "/world dungun : 던전 월드로 감" to player
        send "/world world , /spawn : 테스트월드로 감" to player
        send "&7흠 더있나?" to player

command /tr:
    permission: op
    trigger:
        set {_tr} to chest inventory with 6 rows named "쓰레기통"
        open {_tr} to player

command /메세지테스트:
    permission: op
    trigger:
        broadcast "&f들&k리&f나요...?"
        wait 1 seconds
        broadcast "&f도&k와주&f세요..."
        wait 1 seconds
        broadcast "&f빛도 어&k둠도&f 존&k재하&f지 &k않&f는"
        wait 1 seconds
        broadcast "&f이 공&k허 속&f에서..."
        wait 1 seconds
        broadcast "&f나&k의 꿈&f을..."

command /후원1000 <text>:
	permission: op
	trigger:
		broadcast ""
		broadcast "&3&l[후원] &e%arg-1%님&f, &b1000원 &f후원 감사합니다!"
		broadcast ""

command /강화성공확률지정 <text>:
    permission: op
    trigger:
        set {_num} to arg-1 parsed as number
        set {testProbability} to {_num}
        send "&a[✔] 강화 성공 확률이 %{testProbability}%&a로 설정되었습니다." to player


command /테스트강화:
    permission: op
    trigger:
        if {testProbability} is not set:
            send "&c[✘] 확률이 설정되지 않았습니다. /강화성공확률지정 (예: 55.7)" to player
            stop
        else if {tryCount} is not set:
            set {tryCount} to 0
        set {_random} to random number between 0 and 100
        add 1 to {tryCount}
        send "&7[DEBUG] 랜덤 값: %{_random}% / 설정된 확률: %{testProbability}% / 시도횟수: %{tryCount}%" to player
        if {_random} <= {testProbability}:
            send "&a[✔] 강화 성공!" to player
        else:
            send "&c[✘] 강화 실패..." to player

command /횟수초기화:
    permission: op
    trigger:
        set {tryCount} to 0
        send "&c[✔] 시도 횟수가 초기화되었습니다." to player

command /skrl:
    permission: op
    trigger:
        broadcast "&a[!] &f관리자가 스크립트를 리로드했습니다! &7[ 관리자 : %player% ]"
        execute console command "skript reload all"
        send "&a[✔] 모든 스크립트를 리로드했습니다." to player
