command /히든보스오픈:
	permission: op
	trigger:
		broadcast ""
		broadcast "&e&l[&e★&e&l] &a&l많은 낭만들의 응원&f으로 &d낭만 에너지&f가 모여 &c&l미지의 포탈&f이 생겼습니다."
		broadcast ""
		loop all players:
			play sound "block.end_portal.spawn" to loop-player

command /후원1000 <text>:
	permission: op
	trigger:
		broadcast ""
		broadcast "&3&l[후원] &e%arg-1%님&f, &b1000원 &f후원 감사합니다!"
		broadcast ""

command /강화성공확률지정 <text>:
    permission: op
    trigger:
        set {_num} to arg-1 parsed as number
        set {testProbability} to {_num}
        send "&a[✔] 강화 성공 확률이 %{testProbability}%&a로 설정되었습니다." to player


command /테스트강화:
    permission: op
    trigger:
        if {testProbability} is not set:
            send "&c[✘] 확률이 설정되지 않았습니다. /강화성공확률지정 (예: 55.7)" to player
        else:
            set {_random} to random number between 0 and 100
            send "&7[DEBUG] 랜덤 값: %{_random}% / 설정된 확률: %{testProbability}%" to player
            if {_random} <= {testProbability}:
                send "&a[✔] 강화 성공!" to player
            else:
                send "&c[✘] 강화 실패..." to player

